"""VS Code's settings for this folder (.vscode/settings.json), written per user by the launcher.

Generated, not tracked: chat.disableAIFeatures is window-scoped and this folder's file beats the
user's own, so a Copilot user needs false where Claude/ChatGPT users need true. Editing a tracked
file broke on update (the zip put true back into an open window, Copilot shut mid-chat) and left
developer checkouts dirty (`git pull --ff-only` then fails). Edit the dicts here, never the file.
"""
import json
import re
from pathlib import Path

import cfg
from window import brand

# page look for every .md page (Today, START HERE, Guides, job folders); relative = to this folder
PAGES_CSS = "app/window/pages.css"
START_HERE = "START HERE.md"

DOCUMENT = {
    "editor.lineNumbers": "off",
    "editor.glyphMargin": False,
    "editor.folding": False,
    "editor.stickyScroll.enabled": False,
    "editor.guides.indentation": False,
    "editor.renderLineHighlight": "none",
    "editor.lightbulb.enabled": "off",
    "editor.minimap.enabled": False,
    "editor.wordWrap": "on",
    "editor.occurrencesHighlight": "off",
    "editor.quickSuggestions": {"other": "off", "comments": "off", "strings": "off"},
}

HEADER = "// generated by app/workspace.py at every launch - edit that file, not this one\n"

COMMON = {
    "files.exclude": {
        "app": True,
        "docs": True,
        "**/.data": True,
        ".agents": True,
        ".claude": True,
        ".codex": True,
        ".github": True,
        ".vscode": True,
        ".venv": True,
        ".pytest_cache": True,
        "**/__pycache__": True,
        ".gitattributes": True,
        ".gitignore": True,
        "AGENTS.md": True,
        "CLAUDE.md": True,
        "README.md": True,
        "pyproject.toml": True,
        "uv.lock": True,
    },
    # red underline the moment a resume fact is mistyped, instead of an error hours later at render
    "yaml.schemas": {
        "./app/resume/details.schema.json": "My Resume/Resume details.yml",
    },
    "yaml.validate": True,
    "yaml.format.enable": False,
    # by name => My Jobs reads in pipeline order (1 To apply ... 4 Closed), jobs by number inside;
    # "modified" reshuffled the stages every time a job moved
    "explorer.sortOrder": "default",
    # a stage holding one job stays its own row, not "1 To apply / Job 3 - ..." squeezed on one line
    "explorer.compactFolders": False,
    "workbench.startupEditor": "none",
    "workbench.tips.enabled": False,
    # one program, not a code editor: developer controls out of sight, nothing the user needs gone.
    # Tab buttons + status bar stay: Claude's new-chat and open-chat buttons live there
    # Tabs stay (START HERE, resume, posting side by side); file list + its icons stay, moved to a
    # small row on top (ChatGPT's icon lives there)
    "window.title": cfg.NAME,
    "window.commandCenter": False,
    "workbench.layoutControl.enabled": False,
    "workbench.navigationControl.enabled": False,
    "workbench.activityBar.location": "top",
    "workbench.editor.empty.hint": "hidden",
    "breadcrumbs.enabled": False,
    "explorer.openEditors.visible": 0,
    "editor.minimap.enabled": False,
    # right-hand sidebar shown on open => START HERE / Today in the middle, chat beside it
    "workbench.secondarySideBar.defaultVisibility": "visible",
    # job links open as a tab in this window (VS Code's own browser): its sign-ins + cookies kept for
    # this folder only - the default shares them w/ every VS Code window + profile, kept after uninstall
    "workbench.browser.dataStorage": "workspace",
    # no globe button in the title bar (an experiment can turn it on); links open from the pages
    "workbench.browser.showInTitleBar": False,
    # filling a form in a window tab attaches VS Code's debugger: no floating Pause / Stop bar over
    # the tabs meanwhile (measured hidden, fill the same - app/docs/apply/vscode-browser.md "Built (c)")
    "debug.toolBarLocation": "hidden",
    "extensions.ignoreRecommendations": True,
    "workbench.editorAssociations": {
        "*.md": "vscode.markdown.preview.editor",
        # longer pattern wins; dropped by VS Code when the window's extension is missing => page view
        "Today.md": "cezJobFinder.today",
    },
    # brand look over VS Code's two stock themes: light by default, dark when the computer is dark;
    # light / dark chosen (.data/look, app/look.py) => LOOK below. High contrast always follows the computer
    "window.autoDetectColorScheme": True,
    "workbench.preferredLightColorTheme": "Light Modern",
    "workbench.preferredDarkColorTheme": "Dark Modern",
    "workbench.colorCustomizations": brand.color_customizations(),
    "markdown.styles": [PAGES_CSS],
    "git.openRepositoryInParentFolders": "never",
    "scm.showActionButton": False,
    # Copilot's agent runs its steps in the terminal; panel popping up at the bottom read as a code tool
    "terminal.integrated.hideOnStartup": "always",
    # resume facts + search settings read as documents: no line numbers, folding arrows, guides,
    # lightbulbs. YAML schema underline + hover stay (problems, decorations never touched)
    "[yaml]": DOCUMENT,
    "[markdown]": DOCUMENT,
}

# chosen look (app/look.py) -> fixed theme; brand colorCustomizations cover both themes
LOOK = {
    "light": {"window.autoDetectColorScheme": False, "workbench.colorTheme": "Light Modern"},
    "dark": {"window.autoDetectColorScheme": False, "workbench.colorTheme": "Dark Modern"},
}

EXTENSION_CHAT = {
    # else VS Code's own Copilot chat owns the right-hand panel and the user talks to it, not Claude/ChatGPT
    "chat.disableAIFeatures": True,
    # chat in the right-hand sidebar: the default opens it as a tab and leaves that sidebar empty
    "claudeCode.preferredLocation": "sidebar",
    # no developer checklist in the chat; only prompts + answers, steps one click away
    "claudeCode.hideOnboarding": True,
    "claudeCode.focusView": True,
}


def terminal_commands(allow: list[str]) -> list[str]:
    """Commands .claude/settings.json lets the AI run ("Bash(uv sync*)" -> "uv sync"), once each."""
    found = []
    for rule in allow:
        m = re.fullmatch(r"(?:Bash|PowerShell)\((.+?)\s*\*\)", rule)
        if m and m.group(1) not in found:
            found.append(m.group(1))
    return found


def claude_commands(root: Path | None = None) -> list[str]:
    allow = json.loads(((root or cfg.ROOT) / ".claude" / "settings.json").read_text(encoding="utf-8"))
    return terminal_commands(allow["permissions"]["allow"])


def copilot(home: Path | None = None, root: Path | None = None) -> dict:
    home = home or Path.home()
    return {
        # Copilot's chat is the AI here => VS Code's built-in chat stays on
        "chat.disableAIFeatures": False,
        # agent runs Job Finder's commands; ask/edit modes can't, and the user would not know to switch
        "chat.newSession.defaultMode": "agent",
        # the built-in (Local) harness, pinned: Microsoft flips this default by experiment, and the
        # other harness reads other instruction files + its approvals of the commands below are
        # undocumented (app/docs/app-window.md #Copilot's chat)
        "chat.defaultToCopilotHarness": False,
        # a "Continue?" pause mid-resume stalls a user who doesn't see it: docs say 25, the source
        # 50 or a per-plan experiment value. 150 = a whole tailoring or apply turn, a runaway still stops
        "chat.agent.maxRequests": 150,
        # same steps Claude runs without asking (.claude/settings.json), nothing more - a prompt per
        # step stalls a user who can't judge a command
        "chat.tools.terminal.autoApprove": {command: True for command in claude_commands(root)},
        # else the developer's own ~/.claude/CLAUDE.md loads into a job seeker's chat
        "chat.useClaudeMdFile": False,
        # resume PDF dragged in from where people keep downloads (Claude: Read(~/Downloads/**) etc.);
        # absolute per user - one reason this file is generated
        "github.copilot.chat.additionalReadAccessPaths": [str(home / name) for name in ("Downloads", "Desktop", "Documents")],
        # inline suggestions would type invented facts into Resume details.yml as the user edits it
        "github.copilot.enable": {"*": False},
        "github.copilot.nextEditSuggestions.enabled": False,
        # resume + postings stay in this window's chat, not synced elsewhere
        "chat.sessionSync.enabled": False,
        "github.copilot.chat.workspace.codeSearchExternalIngest.enabled": False,
    }


def settings(ai: str | None, home: Path | None = None, root: Path | None = None, set_up: bool = False,
             look: str = "auto") -> dict:
    """None (nothing chosen yet) => the Claude/ChatGPT window, as before AI choice 3 existed.
    set_up = search settings exist => START HERE ("type set me up") leaves the file list.
    look = auto | light | dark (anything else = auto)."""
    out = {**COMMON, **LOOK.get(look, {}), **(copilot(home, root) if ai == "copilot" else EXTENSION_CHAT)}
    if set_up:
        out["files.exclude"] = {**out["files.exclude"], START_HERE: True}
    return out


def render(ai: str | None, home: Path | None = None, root: Path | None = None, set_up: bool = False,
           look: str = "auto") -> str:
    return HEADER + json.dumps(settings(ai, home, root, set_up, look), indent=2) + "\n"


def write(ai: str | None, path: Path | None = None, home: Path | None = None, root: Path | None = None,
          set_up: bool | None = None, look: str | None = None) -> bool:
    """Only when changed: VS Code reloads the window's settings on every write, open or not.
    set_up None => read now (search settings file exists); look None => read now (.data/look)."""
    import look as looks
    path = path or (cfg.ROOT / ".vscode" / "settings.json")
    text = render(ai, home, root, cfg.config_path().exists() if set_up is None else set_up,
                  looks.current() if look is None else look)
    try:
        if path.read_text(encoding="utf-8") == text:
            return False
    except OSError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True
